import { Injectable } from '@angular/core';

export type ProjectRole = 'owner' | 'collaborator';

export type Project = {
  slug: string;
  title: string;
  image: string;
  imageBackgroundColor: string;
  rol: ProjectRole;
  description: string;
  technologies: readonly string[];
  year?: number;
  products?: readonly string[];
  modules?: readonly string[];
  link?: string;
  sourceCode?: string;
  content: string;
};

const PROJECTS: readonly Project[] = [
  {
    slug: 'emmanuel-mendez-website',
    title: 'Emmanuel Mendez Website',
    image: '/svg/logo--expanded--light.svg',
    imageBackgroundColor: '#20665c40',
    rol: 'owner',
    description: 'Personal portfolio website built with Angular featuring server-side rendering, responsive design, and light/dark theme switching.',
    technologies: ['Angular', 'TypeScript', 'CSS', 'SSR'],
    year: 2026,
    link: 'https://emmanuel-mendez-website.vercel.app/',
    sourceCode: 'https://github.com/emmanuel-mendez/emmanuel-mendez-website',
    content: 'A personal portfolio website showcasing professional experience, skills, and projects. Built with Angular 21, it features server-side rendering for optimal SEO, responsive design with mobile-first approach, and light/dark theme support using CSS light-dark() function.',
  },
  {
    slug: 'astyimar-y-emmanuel',
    title: 'Astyimar y Emmanuel',
    image: '/projects/astyimar-y-emmanuel.png',
    imageBackgroundColor: '#6d578f',
    rol: 'owner',
    description: 'Website for Astyimar y Emmanuel built with Astro featuring server-side rendering, responsive design, and light/dark theme switching.',
    technologies: ['Astro', 'TypeScript', 'CSS'],
    year: 2025,
    link: 'https://astyimar-y-emmanuel.com',
    content: 'Website for Astyimar y Emmanuel showcasing professional experience, skills, and projects. Built with Astro, it features server-side rendering for optimal SEO, responsive design with mobile-first approach, and light/dark theme support using CSS light-dark() function.',
  },
  {
    slug: 'coca-cola',
    title: 'Coca Cola',
    image: '/projects/coca-cola.webp',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Email development for Coca Cola.',
    technologies: ['HTML', 'CSS'],
    products: ['Emails Development'],
    link: 'https://www.coca-cola.com/co/es',
    content: 'Email development project for Coca Cola.',
  },
  {
    slug: 'toyota',
    title: 'Toyota',
    image: '/projects/toyota.webp',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website with Colombia localization and totem ads.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    year: 2026,
    products: ['Website'],
    modules: ['Colombia localization', 'Totem ads'],
    link: 'https://toyota.com.co',
    content: 'Website project for Toyota featuring Colombia localization and totem ads.',
  },
  {
    slug: 'shell',
    title: 'Shell',
    image: '/projects/shell.webp',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website and raffle system with Guatemala localization.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website', 'Raffle system'],
    modules: ['Guatemala localization'],
    link: 'https://www.shell.com.gt',
    content: 'Website and raffle system for Shell featuring Guatemala localization.',
  },
  {
    slug: 'mars',
    title: 'Mars',
    image: '/projects/mars.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'E-commerce project for Mars.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://www.mars.com',
    content: 'E-commerce project for Mars.',
  },
  {
    slug: 'castrol',
    title: 'Castrol',
    image: '/projects/castrol.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'E-commerce project for Castrol.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://www.castrol.com',
    content: 'E-commerce project for Castrol.',
  },
  {
    slug: 'rappi-colombia',
    title: 'Rappi',
    image: '/projects/rappi.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Digital modules developed for Rappi Colombia.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    modules: ['Redención', 'Defensoría', 'Mochilas', 'Blog Rappitendero'],
    link: 'https://www.rappi.com.co',
    content: 'A collection of digital modules developed for Rappi Colombia.',
  },
  {
    slug: 'bancolombia',
    title: 'Bancolombia',
    image: '/projects/bancolombia.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Email development for Bancolombia.',
    technologies: ['HTML', 'CSS'],
    products: ['Emails Development'],
    link: 'https://www.bancolombia.com',
    content: 'Email development project for Bancolombia.',
  },
  {
    slug: 'banistmo',
    title: 'Banistmo',
    image: '/projects/banistmo.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Email development for Banistmo.',
    technologies: ['HTML', 'CSS'],
    products: ['Emails Development'],
    link: 'https://www.banistmo.com',
    content: 'Email development project for Banistmo.',
  },
  {
    slug: 'wompi',
    title: 'Wompi',
    image: '/projects/wompi.png',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website project for Wompi.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    year: 2022,
    products: ['Website'],
    link: 'https://wompi.com/es/co',
    content: 'Website project for Wompi.',
  },
  {
    slug: 'alpina',
    title: 'Alpina',
    image: '/projects/alpina.png',
    imageBackgroundColor: '#0152D1',
    rol: 'collaborator',
    description: 'Quinquenios event landing page for Alpina.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    modules: ['Quinquenios event landing page'],
    link: 'https://alpina.com',
    content: 'Quinquenios event landing page project for Alpina.',
  },
  {
    slug: 'colombina',
    title: 'Colombina',
    image: '/projects/colombina.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website project for Colombina.',
    technologies: ['HTML', 'CSS', 'Javascript'],
    products: ['Website'],
    link: 'https://colombina.com',
    content: 'Website project for Colombina.',
  },
  {
    slug: 'grupo-diana',
    title: 'Grupo Diana',
    image: '/projects/grupo-diana.jpeg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'E-commerce project for Grupo Diana.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    year: 2022,
    products: ['E-commerce'],
    link: 'https://grupodiana.co',
    content: 'E-commerce project for Grupo Diana.',
  },
  {
    slug: 'chillibeans',
    title: 'Chillibeans',
    image: '/projects/chillibeans.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'E-commerce project for Chillibean.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://chillibeans.com',
    content: 'E-commerce project for Chillibean.',
  },
  {
    slug: 'grupo-alen',
    title: 'Grupo Alen',
    image: '/projects/grupo-alen.png',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'E-commerce project for Grupo Alen.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://www.grupoalen.com',
    content: 'E-commerce project for Grupo Alen.',
  },
  {
    slug: 'grupo-uno',
    title: 'Grupo Uno',
    image: '/projects/grupo-uno.png',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website with Nicaragua localization.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    modules: ['Nicaragua localization'],
    content: 'Website project for Grupo Uno featuring Nicaragua localization.',
  },
  {
    slug: 'comfaboy',
    title: 'Comfaboy',
    image: '/projects/comfaboy.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website project for Comfaboy.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['Website'],
    link: 'https://www.comfaboy.org',
    content: 'Website project for Comfaboy.',
  },
  {
    slug: 'expovinos-2021',
    title: 'Expovinos 2021',
    image: '/projects/expovinos.png',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website project for Expovinos 2021.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://expovinocr.com',
    content: 'Website project for Expovinos 2021.',
  },
  {
    slug: 'ultra1plus',
    title: 'Ultra1Plus',
    image: '/projects/ultra1plus.png',
    imageBackgroundColor: '#000000',
    rol: 'collaborator',
    description: 'E-commerce project for Ultra1Plus.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://ultra1plus.com',
    content: 'E-commerce project for Ultra1Plus.',
  },
  {
    slug: 'foodbox',
    title: 'Foodbox',
    image: '/projects/foodbox.png',
    imageBackgroundColor: '#FBA2CA',
    rol: 'collaborator',
    description: 'E-commerce project for Foodbox.',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://foodbox.com.co',
    content: 'E-commerce project for Foodbox.',
  },
  {
    slug: 'dojo',
    title: 'Dojo',
    image: '/projects/dojo.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website and e-commerce project for Dojo.',
    technologies: ['Webflow'],
    products: ['Website', 'E-commerce'],
    link: 'https://www.dojo.care',
    content: 'Website and e-commerce project for Dojo.',
  },
  {
    slug: 'planetife',
    image: '/projects/planetife.svg',
    title: 'Planetife',
    imageBackgroundColor: '#0F4D69',
    rol: 'collaborator',
    description: 'Website project for Planetife.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://planetife.com',
    content: 'Website project for Planetife.',
  },
  {
    slug: 'destiny',
    image: '/projects/destiny.png',
    title: 'Destiny',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website project for Destiny.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://www.destiny.ws/',
    content: 'Website project for Destiny.',
  },
  {
    slug: 'dosmass',
    image: '/projects/dosmass.svg',
    title: 'Dosmass',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website project for Dosmass.',
    technologies: ['Webflow'],
    products: ['Website'],
    link: 'https://dosmass.com/',
    content: 'Website project for Dosmass.',
  },
  {
    slug: 'geekboss',
    image: '/projects/geekboss.png',
    title: 'Geekboss',
    imageBackgroundColor: '#000000',
    rol: 'collaborator',
    description: 'Website project for Geekboss.',
    technologies: ['Webflow'],
    products: ['Website'],
    link: 'https://geekboss.co',
    content: 'Website project for Geekboss.',
  },
  {
    slug: 'highpeak',
    title: 'Highpeak',
    image: '/projects/highpeak.svg',
    imageBackgroundColor: '#000000',
    rol: 'collaborator',
    description: 'Website project for Highpeak.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    content: 'Website project for Highpeak.',
  },
  {
    slug: 'adresles',
    image: '/projects/adresles.png',
    title: 'Adresles',
    imageBackgroundColor: '#000000',
    rol: 'collaborator',
    description: 'Website project for Adresles.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://adresles.com/',
    content: 'Website project for Adresles.',
  },
  {
    slug: 'especialistas-en-casa',
    image: '/projects/especialistas-en-casa.png',
    title: 'Especialistas En Casa',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website project for Especialistas En Casa.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://especialistasencasa.com',
    content: 'Website project for Especialistas En Casa.',
  },
  {
    slug: 'dra-skin',
    image: '/projects/dra-skin.svg',
    title: 'Dra Skin',
    imageBackgroundColor: '#000000',
    rol: 'collaborator',
    description: 'Website and e-commerce project for Dra Skin.',
    technologies: ['Webflow'],
    products: ['Website', 'E-commerce'],
    link: 'https://www.draskin.co',
    content: 'Website and e-commerce project for Dra Skin.',
  },
  {
    slug: 'cimonamia',
    image: '/projects/cimonamia.png',
    title: 'Cimonamía',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website and e-commerce project for Cimonamia.',
    technologies: ['Webflow'],
    products: ['Website', 'E-commerce'],
    link: 'https://www.cimonamia.com',
    content: 'Website and e-commerce project for Cimonamia.',
  },
  {
    slug: 'q-buen-plan',
    image: '/projects/qbuenplan.png',
    title: 'Q Buen Plan',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Website with a travel agency system.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    modules: ['Travel Agency System'],
    link: 'https://www.instagram.com/qbuenplanoficial',
    content: 'Website project featuring a travel agency system.',
  },
  {
    slug: 'grateful',
    title: 'Grateful',
    image: '/projects/grateful.svg',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Web application with a movie character archetype recommendation system.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Web Application'],
    modules: ['Brand strategy recommendation system based on movie character archetypes'],
    content: 'Web application featuring a brand strategy recommendation system based on movie character archetypes.',
  },
  {
    slug: 'm374',
    image: '/projects/m374.svg',
    title: 'M374',
    imageBackgroundColor: '#ffffff',
    rol: 'collaborator',
    description: 'Renting virtual spaces in the metaverse.',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    content: 'Renting virtual spaces in the metaverse.',
  },
];

@Injectable({ providedIn: 'root' })
export class ProjectsData {
  public readonly projects: readonly Project[] = PROJECTS;

  public getBySlug(slug: string): Project | undefined {
    return this.projects.find((project) => project.slug === slug);
  }
}
