import { Injectable } from '@angular/core';

export type ProjectRole = 'owner' | 'collaborator';

export type Project = {
  slug: string;
  title: string;
  rol: ProjectRole;
  description: string;
  icon: string;
  technologies: readonly string[];
  year?: number;
  products?: readonly string[];
  modules?: readonly string[];
  link?: string;
  sourceCode?: string;
  content: string;
};

const PROJECTS: readonly Project[] = [
  {
    slug: 'emmanuel-mendez-website',
    title: 'Emmanuel Mendez Website',
    rol: 'owner',
    description:
      'Personal portfolio website built with Angular featuring server-side rendering, responsive design, and light/dark theme switching.',
    icon: 'web',
    technologies: ['Angular', 'TypeScript', 'CSS', 'SSR'],
    year: 2025,
    link: 'https://emmanuel-mendez-website.vercel.app/',
    sourceCode: 'https://github.com/emmanuel-mendez/emmanuel-mendez-website',
    content:
      'A personal portfolio website showcasing professional experience, skills, and projects. Built with Angular 21, it features server-side rendering for optimal SEO, responsive design with mobile-first approach, and light/dark theme support using CSS light-dark() function.',
  },
  {
    slug: 'coca-cola',
    title: 'Coca Cola',
    rol: 'collaborator',
    description: 'Email development for Coca Cola.',
    icon: 'mail',
    technologies: ['HTML', 'CSS'],
    products: ['Emails Development'],
    link: 'https://www.coca-cola.com/co/es',
    content: 'Email development project for Coca Cola.',
  },
  {
    slug: 'toyota',
    title: 'Toyota',
    rol: 'collaborator',
    description: 'Website with Colombia localization and totem ads.',
    icon: 'web',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['Website'],
    modules: ['Colombia localization', 'Totem ads'],
    link: 'https://toyota.com.co',
    content: 'Website project for Toyota featuring Colombia localization and totem ads.',
  },
  {
    slug: 'shell',
    title: 'Shell GT',
    rol: 'collaborator',
    description: 'Website and raffle system with Guatemala localization.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website', 'Raffle system'],
    modules: ['Guatemala localization'],
    link: 'https://www.shell.com.gt',
    content: 'Website and raffle system for Shell featuring Guatemala localization.',
  },
  {
    slug: 'toyota-totem',
    title: 'Toyota Totem',
    rol: 'collaborator',
    description: 'Totem advertising module for Toyota.',
    icon: 'web',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['Website'],
    modules: ['Totem ads'],
    link: 'https://toyota.com.co',
    content: 'Totem advertising module developed for Toyota.',
  },
  {
    slug: 'mars',
    title: 'Mars',
    rol: 'collaborator',
    description: 'E-commerce project for Mars.',
    icon: 'shopping_cart',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://www.mars.com',
    content: 'E-commerce project for Mars.',
  },
  {
    slug: 'castrol',
    title: 'Castrol',
    rol: 'collaborator',
    description: 'E-commerce project for Castrol.',
    icon: 'shopping_cart',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://www.castrol.com',
    content: 'E-commerce project for Castrol.',
  },
  {
    slug: 'bancolombia',
    title: 'Bancolombia',
    rol: 'collaborator',
    description: 'Email development for Bancolombia.',
    icon: 'mail',
    technologies: ['HTML', 'CSS'],
    products: ['Emails Development'],
    link: 'https://www.bancolombia.com',
    content: 'Email development project for Bancolombia.',
  },
  {
    slug: 'rappi-colombia',
    title: 'Rappi',
    rol: 'collaborator',
    description: 'Digital modules developed for Rappi Colombia.',
    icon: 'web',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    modules: ['Redención', 'Defensoría', 'Mochilas', 'Blog Rappitendero'],
    link: 'https://www.rappi.com.co',
    content: 'A collection of digital modules developed for Rappi Colombia.',
  },
  {
    slug: 'rappi-redencion',
    title: 'Rappi Redención',
    rol: 'collaborator',
    description: 'Redención module developed for Rappi.',
    icon: 'web',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    modules: ['Redención'],
    link: 'https://www.rappi.com.co',
    content: 'Redención module developed for Rappi.',
  },
  {
    slug: 'rappi-defensoria',
    title: 'Rappi Defensoría',
    rol: 'collaborator',
    description: 'Defensoría module developed for Rappi.',
    icon: 'web',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    modules: ['Defensoría'],
    link: 'https://www.rappi.com.co',
    content: 'Defensoría module developed for Rappi.',
  },
  {
    slug: 'rappi-mochilas',
    title: 'Rappi Mochilas',
    rol: 'collaborator',
    description: 'Mochilas module developed for Rappi.',
    icon: 'web',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    modules: ['Mochilas'],
    link: 'https://www.rappi.com.co',
    content: 'Mochilas module developed for Rappi.',
  },
  {
    slug: 'blog-rappitenderos',
    title: 'Blog Rappitenderos',
    rol: 'collaborator',
    description: 'Blog Rappitendero module developed for Rappi.',
    icon: 'web',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    modules: ['Blog Rappitendero'],
    link: 'https://www.rappi.com.co',
    content: 'Blog Rappitendero module developed for Rappi.',
  },
  {
    slug: 'colombina',
    title: 'Colombina',
    rol: 'collaborator',
    description: 'Website project for Colombina.',
    icon: 'web',
    technologies: ['HTML', 'CSS', 'Javascript'],
    products: ['Website'],
    link: 'https://colombina.com',
    content: 'Website project for Colombina.',
  },
  {
    slug: 'grupo-diana',
    title: 'Grupo Diana',
    rol: 'collaborator',
    description: 'E-commerce project for Grupo Diana.',
    icon: 'shopping_cart',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://grupodiana.co',
    content: 'E-commerce project for Grupo Diana.',
  },
  {
    slug: 'wompi',
    title: 'Wompi',
    rol: 'collaborator',
    description: 'Website project for Wompi.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://wompi.com/es/co',
    content: 'Website project for Wompi.',
  },
  {
    slug: 'banistmo',
    title: 'Banistmo',
    rol: 'collaborator',
    description: 'Email development for Banistmo.',
    icon: 'mail',
    technologies: ['HTML', 'CSS'],
    products: ['Emails Development'],
    link: 'https://www.banistmo.com',
    content: 'Email development project for Banistmo.',
  },
  {
    slug: 'grupo-alen',
    title: 'Grupo Alen',
    rol: 'collaborator',
    description: 'E-commerce project for Grupo Alen.',
    icon: 'shopping_cart',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://www.grupoalen.com',
    content: 'E-commerce project for Grupo Alen.',
  },
  {
    slug: 'comfaboy',
    title: 'Comfaboy',
    rol: 'collaborator',
    description: 'Website project for Comfaboy.',
    icon: 'web',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['Website'],
    link: 'https://www.comfaboy.org',
    content: 'Website project for Comfaboy.',
  },
  {
    slug: 'grupo-uno',
    title: 'Grupo Uno Nicaragua',
    rol: 'collaborator',
    description: 'Website with Nicaragua localization.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    modules: ['Nicaragua localization'],
    content: 'Website project for Grupo Uno featuring Nicaragua localization.',
  },
  {
    slug: 'grupo-uno-honduras',
    title: 'Grupo Uno Honduras',
    rol: 'collaborator',
    description: 'Website with Honduras localization.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    modules: ['Honduras localization'],
    content: 'Website project for Grupo Uno featuring Honduras localization.',
  },
  {
    slug: 'expovinos-2021',
    title: 'Expovinos 2021',
    rol: 'collaborator',
    description: 'Website project for Expovinos 2021.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://expovinocr.com',
    content: 'Website project for Expovinos 2021.',
  },
  {
    slug: 'foodbox',
    title: 'Foodbox',
    rol: 'collaborator',
    description: 'E-commerce project for Foodbox.',
    icon: 'shopping_cart',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://foodbox.com.co',
    content: 'E-commerce project for Foodbox.',
  },
  {
    slug: 'chillibeans',
    title: 'Chillibean',
    rol: 'collaborator',
    description: 'E-commerce project for Chillibean.',
    icon: 'shopping_cart',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://chillibeans.com',
    content: 'E-commerce project for Chillibean.',
  },
  {
    slug: 'alpina',
    title: 'Alpina Quinquenios',
    rol: 'collaborator',
    description: 'Quinquenios event landing page for Alpina.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    modules: ['Quinquenios event landing page'],
    link: 'https://alpina.com',
    content: 'Quinquenios event landing page project for Alpina.',
  },
  {
    slug: 'ultra1plus',
    title: 'Ultra1Plus',
    rol: 'collaborator',
    description: 'E-commerce project for Ultra1Plus.',
    icon: 'shopping_cart',
    technologies: ['Typescript', 'Next.js', 'Storybook'],
    products: ['E-commerce'],
    link: 'https://ultra1plus.com',
    content: 'E-commerce project for Ultra1Plus.',
  },
  {
    slug: 'dojo',
    title: 'Dojo',
    rol: 'collaborator',
    description: 'Website and e-commerce project for Dojo.',
    icon: 'web',
    technologies: ['Webflow'],
    products: ['Website', 'E-commerce'],
    link: 'https://www.dojo.care',
    content: 'Website and e-commerce project for Dojo.',
  },
  {
    slug: 'highpeak',
    title: 'Highpeak',
    rol: 'collaborator',
    description: 'Website project for Highpeak.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    content: 'Website project for Highpeak.',
  },
  {
    slug: 'grateful',
    title: 'Grateful',
    rol: 'collaborator',
    description: 'Web application with a movie character archetype recommendation system.',
    icon: 'movie',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Web Application'],
    modules: ['Brand strategy recommendation system based on movie character archetypes'],
    content:
      'Web application featuring a brand strategy recommendation system based on movie character archetypes.',
  },
  {
    slug: 'especialistas-en-casa',
    title: 'Especialistas En Casa',
    rol: 'collaborator',
    description: 'Website project for Especialistas En Casa.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://especialistasencasa.com',
    content: 'Website project for Especialistas En Casa.',
  },
  {
    slug: 'q-buen-plan',
    title: 'Q Buen Plan',
    rol: 'collaborator',
    description: 'Website with a travel agency system.',
    icon: 'travel_explore',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    modules: ['Travel Agency System'],
    link: 'https://www.instagram.com/qbuenplanoficial',
    content: 'Website project featuring a travel agency system.',
  },
  {
    slug: 'geekboss',
    title: 'Geekboss',
    rol: 'collaborator',
    description: 'Website project for Geekboss.',
    icon: 'web',
    technologies: ['Webflow'],
    products: ['Website'],
    link: 'https://geekboss.co',
    content: 'Website project for Geekboss.',
  },
  {
    slug: 'dra-skin',
    title: 'Dra Skin',
    rol: 'collaborator',
    description: 'Website and e-commerce project for Dra Skin.',
    icon: 'shopping_cart',
    technologies: ['Webflow'],
    products: ['Website', 'E-commerce'],
    link: 'https://www.draskin.co',
    content: 'Website and e-commerce project for Dra Skin.',
  },
  {
    slug: 'planetife',
    title: 'Planetife',
    rol: 'collaborator',
    description: 'Website project for Planetife.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://planetife.com',
    content: 'Website project for Planetife.',
  },
  {
    slug: 'destiny',
    title: 'Destiny Website',
    rol: 'collaborator',
    description: 'Website project for Destiny.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://www.destiny.ws/',
    content: 'Website project for Destiny.',
  },
  {
    slug: 'dosmass',
    title: 'Dosmass',
    rol: 'collaborator',
    description: 'Website project for Dosmass.',
    icon: 'web',
    technologies: ['Webflow'],
    products: ['Website'],
    link: 'https://dosmass.com/',
    content: 'Website project for Dosmass.',
  },
  {
    slug: 'adresles',
    title: 'Adresles',
    rol: 'collaborator',
    description: 'Website project for Adresles.',
    icon: 'web',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    link: 'https://adresles.com/',
    content: 'Website project for Adresles.',
  },
  {
    slug: 'm374',
    title: 'M374 Meta',
    rol: 'collaborator',
    description: 'Renting virtual spaces in the metaverse.',
    icon: 'view_in_ar',
    technologies: ['Typescript', 'Angular', 'Storybook'],
    products: ['Website'],
    content: 'Renting virtual spaces in the metaverse.',
  },
  {
    slug: 'agro-platform',
    title: 'Agro Platform',
    rol: 'collaborator',
    description: 'Agro Platform project.',
    icon: 'web',
    technologies: [],
    products: ['Web Application'],
    content: 'Agro Platform project.',
  },
];

@Injectable({ providedIn: 'root' })
export class ProjectsData {
  public readonly projects: readonly Project[] = PROJECTS;

  public getBySlug(slug: string): Project | undefined {
    return this.projects.find((project) => project.slug === slug);
  }
}
